# Generated by Django 5.1.7 on 2025-03-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteease_app', '0003_candidate_award_education_leadershipexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voteease_app.position'),
        ),
    ]
