# Generated by Django 5.1.7 on 2025-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteease_app', '0004_alter_candidate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='ps_image',
            field=models.ImageField(blank=True, null=True, upload_to='ps_images/'),
        ),
    ]
